theme: jekyll-theme-slate
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: Automation of Home Lighting with Learned BLE Positioning
description: Project for UCLA ECEM202A/CSM213A (Fall 2021)
